mlnet_pc4/Models/ErrorViewModel.cs
namespace MLNETAPP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

mlnet_pc4/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using mlnet_pc4.Models;
using System.Diagnostics;

namespace mlnet_pc4.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

mlnet_pc4/Controllers/mlnetController.cs
using Microsoft.AspNetCore.Mvc;

using mlnet_pc4;




namespace mlnet_pc4.Controllers

{

	public class mlnetController : Controller

	{

		public IActionResult Index()

		{

			return View();

		}




		[HttpPost]

		public IActionResult mlnet(string text)

		{

            //Load sample data

            var sampleData = new SentimentModel.ModelInput()

            {

                Col0 = text

            };







            //Load model and predict output

            var result = SentimentModel.Predict(sampleData);

			Console.WriteLine(result.PredictedLabel);

            return View("Index", result);

		}




	}

}

mlnet_pc4/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

mlnet_pc4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mlnet_pc4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mlnet_pc4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mlnet_pc4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - mlnet_pc4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

mlnet_pc4/Views/mlnet/Index.cshtml
@{
    ViewData["Title"] = "View";
}

<h1>EVALUAR MODELO </h1>

<form asp-controller="mlnet" asp-action="mlnet" method="post">
        <label for="textInput">Texto a evaluar: </label>
        <input type="text" id="textInput" name="textInput" class="form-control" required>
    <br />
    <button type="submit" class="btn btn-primary">Evaluar</button>
</form>
<br />
<div>
    <p>
        @if(@Model != null)
        {
            @if (@Model.PredictedLabel == 1)
            {
                <span>El sentimiento es POSITIVO. </span>
            }
            else if(Model.PredictLabel == 0)
            {
                <span>El sentimiento es NEGATIVO.</span>
            }
        }
        </p>
    </div>